### ISSUE TITLE
MeasureReport resources for EXM130 R4 contain invalid references

### ISSUE THREAD

**Issue by mgramigna** [DBCG/connectathon#24] opened 2019-12-16 13:47 UTC
When trying to post [this bundle](https://github.com/DBCG/connectathon/blob/master/fhir4/bundles/EXM130_FHIR4-7.2.000/EXM130_FHIR4-7.2.000-bundle.json) to cqf-ruler, I get a 400 bad request due to references in the MeasureReport resources.

Some of the references in the MeasureReport resources just specify an `id`, rather than `ResourceType/id`, and cqf-ruler cannot resolve these. See [here](https://github.com/DBCG/connectathon/blob/0743e9ec8ab3c78dee3552e7d6dc289d0558f45e/fhir4/bundles/EXM130_FHIR4-7.2.000/EXM130_FHIR4-7.2.000-files/measurereport-EXM130-FHIR4-7.2.000-denom.json#L190-L193) and [here](https://github.com/DBCG/connectathon/blob/0743e9ec8ab3c78dee3552e7d6dc289d0558f45e/fhir4/bundles/EXM130_FHIR4-7.2.000/EXM130_FHIR4-7.2.000-files/measurereport-EXM130-FHIR4-7.2.000-numer.json#L269-L271) for the lines that cause this.

**Comment by rob-reynolds** [comment] 2019-12-16 15:51
Thank you.

The bundle is fixed in the repo.

Root cause looks like an issue in Measure Report generation in the CQF Ruler.   Logging an issue to research there.

**Comment by mgramigna** [comment] 2019-12-16 16:13
@rob-reynolds Thanks! I see that you updated the `subject` references, but the `measure` references in the `MeasureReports` also need to be updated to be `Measure/id`. 

Thanks for logging the cqf-ruler issue!

**Comment by rob-reynolds** [comment] 2019-12-16 18:08
I pushed a second commit: c411890c8904af1ba8e7c8bfeff79ee59b43d4ad.

There was also an issue with some references including "history".

All should be fixed now.

**Closed by rob-reynolds** 2019-12-16 18:08 UTC
